TheWebShop.WebApp/Pages/Basket.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Newtonsoft.Json;

using TheWebShop.Common.Dtos;
using TheWebShop.Common.Models;
using TheWebShop.Data.Entities.User;
using TheWebShop.Services.BasketService;
using TheWebShop.Services.EntityServices.ProductService;
using TheWebShop.Services.OrderingService;

namespace TheWebShop.WebApp.Pages
{
    public class BasketModel : PageModel
    {
        private readonly SignInManager<UserEntity> _singInManager;

        private readonly UserManager<UserEntity> _userManager;

        private readonly IProductService _productService;

        private readonly IBasketService _basketService;

        private readonly IOrderingService _orderingService;

        public Common.Models.BasketModel Basket { get; set; } = new Common.Models.BasketModel();

        [BindProperty]
        public int ProductToBeRemoved { get; set; }

        public BasketModel(
            IProductService productService,
            IBasketService basketService,
            IOrderingService orderingService,
            SignInManager<UserEntity> signInManager,
            UserManager<UserEntity> userManager
        )
        {
            _productService = productService;
            _basketService = basketService;
            _orderingService = orderingService;

            _singInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            Basket = await _basketService.GetBasket(HttpContext);

            foreach (var item in Basket.Items)
            {
                item.Product = await _productService.GetById<ProductDto>(item.ProductEntityId);
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            Basket = await _basketService.EditBasket(HttpContext, Request.Form);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostClearBasketAsync()
        {
            await _basketService.ClearBasket(HttpContext);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostPlaceOrderAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            var order = await _orderingService.CreateOrder(await _basketService.GetBasket(HttpContext), user);
            await _basketService.ClearBasket(HttpContext);

            return RedirectToPage("/Order", new {OrderId = order.EntityId});
        }
    }
}

TheWebShop.WebApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;

namespace TheWebShop.WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger _logger;

        public ErrorModel(ILogger logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TheWebShop.WebApp/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheWebShop.Common.Dtos;
using TheWebShop.Common.Filters.Product;
using TheWebShop.Services.EntityServices.ProductService;

namespace TheWebShop.WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IProductService _productService;

        public IEnumerable<ProductWithPicturesDto> NewestProducts { get; set; }
        
        public IEnumerable<ProductWithPicturesDto> MostPopularProducts { get; set; }


        public IndexModel(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            NewestProducts = await _productService.GetByFilter<ProductWithPicturesDto>(new ProductFilter() { OrderBy = ProductOrderBy.CreatedAtDesc, PrioritizeHighlighted = false, PageSize = 4 });
            
            MostPopularProducts = await _productService.GetByFilter<ProductWithPicturesDto>(new ProductFilter() { OrderBy = ProductOrderBy.ReviewsDesc, PrioritizeHighlighted = false, PageSize = 4 });
            
            return Page();
        }
    }
}

TheWebShop.WebApp/Pages/Order.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using TheWebShop.Common.Dtos;
using TheWebShop.Services.EntityServices.OrderService;

namespace TheWebShop.WebApp.Pages
{
    public class OrderModel : PageModel
    {
        private readonly IOrderService _orderService;

        public OrderModel(IOrderService orderService)
        {
            _orderService = orderService;
        }

        [BindProperty(SupportsGet = true)]
        public int OrderId { get; set; }

        [BindProperty]
        public OrderDto Order { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            Order = await _orderService.GetById<OrderDto>(OrderId);
            return Page();
        }
    }
}

TheWebShop.WebApp/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;

namespace TheWebShop.WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger _logger;

        public PrivacyModel(ILogger logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TheWebShop.WebApp/Pages/Basket.cshtml
@page
@using TheWebShop.Data.Entities.User
@model BasketModel
@inject SignInManager<UserEntity> SignInManager
@inject UserManager<UserEntity> UserManager
@{
    ViewData["Title"] = "Basket";
}

<form id="basketForm" method="post">

    <div class="row">
        <div class="col-md-8">
            @if (Model.Basket?.Items.Count > 0)
            {
                <div class="d-flex align-items-center justify-content-between">
                    <div>
                        <h3 class="m-0">Basket</h3>
                        <small class="d-block text-muted mb-2">Donec vitae erat hendrerit, hendrerit lectus at, faucibus odio.</small>
                    </div>

                    <div class="d-flex align-items-center justify-content-center">
                        <button asp-page-handler="ClearBasket" class="btn btn-light btn-sm mr-1">
                            @* <i class="fas fa-trash fa-fw"></i> *@
                            Clear basket
                        </button>
                        <button class="btn btn-light btn-sm">
                            <i class="fas fa-sync fa-fw"></i>
                        </button>
                    </div>

                </div>

                <table class="table table-bordered">
                    <tbody>

                    @foreach (var group in Model.Basket.Items.OrderBy(x => x.Product.Brand.Name).GroupBy(x => x.Product.Brand.Name))
                    {
                        <tr>
                            <th colspan="3">
                                @group.Key
                            </th>
                        </tr>

                        @foreach (var item in group)
                        {
                            <tr>
                                <td>@item.Product.Name</td>
                                <td>
                                    <input class="form-control" style="max-width: fit-content" type="number" name="@item.ProductEntityId" value="@item.Quantity"/>
                                </td>
                                <td class="text-right text-monospace">@($"{item.Quantity * item.Product.Price:c}")</td>
                            </tr>
                        }
                    }

                    <tr>
                        <td colspan="2" class="text-center text-muted text-monospace" style="font-size: 1.125pc">@Model.Basket.Items.Sum(x => x.Quantity)</td>
                        <td class="text-right text-muted text-monospace" style="font-size: 1.125pc">
                            <small>eksl. moms</small> @($"{Model.Basket.Items.Sum(x => x.Quantity * x.Product.Price):c}")
                        </td>
                    </tr>
                    <tr>
                        <th colspan="3" class="text-right text-monospace" style="font-size: 1.25pc">
                            <small>inkl. moms</small> @($"{Model.Basket.Items.Sum(x => x.Quantity * x.Product.Price) * 1.25M:c}")
                        </th>
                    </tr>

                    </tbody>
                </table>

                <input id="productToBeRemoved" type="hidden" asp-for="@Model.ProductToBeRemoved"/>

                <script>
                    $(document).ready(function() {
                        $(".js-remove").click(function(e) {
                            $("#productToBeRemoved").val(this.dataset.productid);
                            $("#basketForm").submit();
                        });
                    });
                </script>
            }
            else
            {
                <small class="d-block text-muted text-center">You have no products in your cart.</small>
            }
        </div>

        <div class="col-md-4">
            @if (SignInManager.IsSignedIn(User))
            {
                <h4>Ordering</h4>
                <p class="text-justify">When you're ready to place your order, simply press the button below...</p>
                <button class="btn btn-light btn-block" asp-page-handler="PlaceOrder">Place order</button>
            }
            else
            {
                <h4>Login or Register</h4>
                <p class="text-justify">You have to login or register a new account to make an order.</p>
                <div class="d-flex">
                    <a class="btn btn-light btn-block mr-2" asp-page="/Account/Login">Login</a>
                    <a class="btn btn-light btn-block mt-0" asp-page="/Account/Register">Register</a>
                </div>
            }
        </div>
    </div>


</form>

TheWebShop.WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    ViewData["ShowHero"] = true;
}

<div class="text-justify">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin velit quam, non mattis purus ultricies eget.
    Quisque imperdiet turpis eu augue fringilla dapibus. Nullam leo sem, facilisis a faucibus vel, scelerisque vitae ipsum.
    Quisque in malesuada nibh, sed convallis neque. Nam urna neque, ultrices ornare magna at, placerat eleifend sapien.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet placerat massa.
    Aenean magna lorem, consequat ut ex in, vestibulum iaculis purus. Vestibulum finibus urna ipsum, ut maximus dolor ullamcorper vel.
    Suspendisse pharetra fringilla interdum. Ut egestas enim sed justo vestibulum blandit.
    Aliquam euismod dapibus felis, ut pellentesque lacus tempor non.
</div>

<section class="d-flex flex-column mt-5">
    <div class="d-flex flex-column align-items-start mb-3">
        <h3 class="m-0">Most Popular Products</h3>
        <small class="text-muted">Duis fermentum ligula ac facilisis malesuada. Etiam vitae massa libero.</small>
    </div>

    <div style="display:grid; grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr));grid-gap:1rem;">

        @foreach (var product in Model.MostPopularProducts)
        {
            @await Html.PartialAsync("Shared/Partials/ProductCard", product)
        }

    </div>
</section>

<section class="d-flex flex-column mt-5">
    <div class="d-flex flex-column align-items-start mb-3">
        <h3 class="m-0">Newest Products</h3>
        <small class="text-muted">Duis fermentum ligula ac facilisis malesuada. Etiam vitae massa libero.</small>
    </div>

    <div style="display:grid; grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr));grid-gap:1rem;">

        @foreach (var product in Model.NewestProducts)
        {
            @await Html.PartialAsync("Shared/Partials/ProductCard", product)
        }

    </div>
</section>

<section class="d-flex flex-column align-items-center mt-5">
    <a asp-page="/Products/Index" class="text-decoration-none">
        <h5 class="m-0 text-muted">See all products...</h5>
    </a>
</section>

TheWebShop.WebApp/Pages/Order.cshtml
@page "{OrderId:int}"
@model OrderModel
@{
}

<div class="row mb-5">
    <div class="col-md-3">
        <strong>WE <i class="fas fa-heart text-danger"></i> DRUGS</strong>
        <div>Skovvej 20, 244</div>
        <div>6400 Sønderborg</div>
        <div>contact@welovedrugs.com</div>
    </div>
</div>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>Brand</th>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Order.Items)
    {
        <tr>
            <td>@item.Product.Brand.Name</td>
            <td>@item.Product.Name</td>
            <td>@item.PricePerProduct</td>
            <td>@item.Quantity</td>
            <td>@item.Total</td>
        </tr>
    }
    <tr>
        <td rowspan="2" class="text-center text-monospace align-middle text-muted" style="font-size: 1.125pc">
            @Model.Order.TotalQuantity
        </td>
        <td colspan="4" class="text-muted text-right text-monospace" style="font-size: 1.125pc">
            <small>eksl. moms</small> @($"{Model.Order.Total:C}")
        </td>
    </tr>
    <tr>
        <td colspan="4" class="text-right text-monospace" style="font-size: 1.25pc">
            <small>inkl. moms</small> @($"{(Model.Order.Total + Model.Order.TotalTax):C}")
        </td>
    </tr>
    </tbody>
</table>