TheWebShop.WebApp/Pages/Admin/Brands/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

using AutoMapper;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

using TheWebShop.Common.Dtos;
using TheWebShop.Common.Filters.Brand;
using TheWebShop.Common.Models.Forms;
using TheWebShop.Data.Entities.Brand;
using TheWebShop.Data.Entities.Product;
using TheWebShop.Services.EntityServices.BrandService;

namespace TheWebShop.WebApp.Pages.Admin.Brands
{
    public class CreateModel : PageModel
    {
        private readonly IBrandService _brandService;

        private readonly IMapper _mapper;

       [BindProperty]
        public BrandFormModel FormModel { get; set; }

        public CreateModel(IBrandService brandService, IMapper mapper)
        {
            _brandService = brandService;
            _mapper = mapper;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return OnGet();
            }

            var entity = _mapper.Map<BrandEntity>(FormModel);

            await _brandService.Create<BrandDto>(entity);

            return RedirectToPage();
        }
    }
}

TheWebShop.WebApp/Pages/Admin/Brands/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using TheWebShop.Common.Dtos;
using TheWebShop.Services.EntityServices.BrandService;

namespace TheWebShop.WebApp.Pages.Admin.Brands
{
    public class DeleteModel : PageModel
    {
        private readonly IBrandService _brandService;

        public BrandDto Brand { get; set; }

        public DeleteModel(IBrandService brandService)
        {
            _brandService = brandService;
        }

        public async Task<IActionResult> OnGetAsync([FromRoute] int entityId)
        {
            Brand = await _brandService.GetById<BrandDto>(entityId);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromRoute] int entityId)
        {
            await _brandService.DeleteById(entityId);
            return RedirectToPage("Index");
        }
    }
}

TheWebShop.WebApp/Pages/Admin/Brands/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

using AutoMapper;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

using TheWebShop.Common.Dtos;
using TheWebShop.Common.Filters.Brand;
using TheWebShop.Common.Filters.Product;
using TheWebShop.Common.Models.Forms;
using TheWebShop.Common.Models.Product;
using TheWebShop.Services.EntityServices.BrandService;
using TheWebShop.Services.EntityServices.ProductService;

namespace TheWebShop.WebApp.Pages.Admin.Brands
{
    public class EditModel : PageModel
    {
        private readonly IBrandService _brandService;

        private readonly IMapper _mapper;

        public BrandDto Brand { get; set; }

        [BindProperty]
        public BrandFormModel FormModel { get; set; }

        public EditModel(IBrandService brandService, IMapper mapper)
        {
            _brandService = brandService;

            _mapper = mapper;
        }

        public async Task<IActionResult> OnGetAsync([FromRoute] int entityId)
        {
            Brand = await _brandService.GetById<BrandDto>(entityId);

            FormModel = _mapper.Map<BrandFormModel>(Brand);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromRoute] int entityId)
        {
            if (!ModelState.IsValid)
            {
                return await OnGetAsync(entityId);
            }

            var brand = await _brandService.UpdateById<BrandDto>(entityId, FormModel);

            return RedirectToPage();
        }
    }
}

TheWebShop.WebApp/Pages/Admin/Categories/Create.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using TheWebShop.Common.Dtos;
using TheWebShop.Common.Filters.Category;
using TheWebShop.Common.Models.Forms;
using TheWebShop.Data.Entities.Category;
using TheWebShop.Services.EntityServices.CategoryService;

namespace TheWebShop.WebApp.Pages.Admin.Categories
{
    public class CreateModel : PageModel
    {
        private readonly ICategoryService _categoryService;

        private readonly IMapper _mapper;

        public SelectList Categories { get; set; }

        [BindProperty]
        public CategoryFormModel FormModel { get; set; }

        public CreateModel(ICategoryService reviewService, IMapper mapper)
        {
            _categoryService = reviewService;

            _mapper = mapper;
        }

        public async Task<IActionResult> OnGetAsync([FromRoute] int entityId)
        {
            var _categories = await _categoryService.GetByFilter<CategoryDto>(new CategoryFilter() { IncludeInactive = true });
            Categories = new SelectList(_categories.OrderBy(x => x.Name), nameof(CategoryDto.EntityId), nameof(CategoryDto.Name));

            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromRoute] int entityId)
        {
            if (!ModelState.IsValid)
            {
                return await OnGetAsync(entityId);
            }

            var entity = _mapper.Map<CategoryEntity>(FormModel);
            await _categoryService.Create<CategoryDto>(entity);

            return RedirectToPage();
        }
    }
}

TheWebShop.WebApp/Pages/Admin/Categories/Delete.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheWebShop.Common.Dtos;
using TheWebShop.Services.EntityServices.CategoryService;

namespace TheWebShop.WebApp.Pages.Admin.Categories
{
    public class DeleteModel : PageModel
    {
        private readonly ICategoryService _categoryService;

        public CategoryDto Category { get; set; }

        public DeleteModel(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> OnGetAsync([FromRoute] int entityId)
        {
            Category = await _categoryService.GetById<CategoryDto>(entityId);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromRoute] int entityId)
        {
            await _categoryService.DeleteById(entityId);
            return RedirectToPage("Index");
        }
    }
}

TheWebShop.WebApp/Pages/Admin/Categories/Edit.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using TheWebShop.Common.Dtos;
using TheWebShop.Common.Filters.Category;
using TheWebShop.Common.Models.Forms;
using TheWebShop.Services.EntityServices.CategoryService;

namespace TheWebShop.WebApp.Pages.Admin.Categories
{
    public class EditModel : PageModel
    {
        private readonly ICategoryService _categoryService;

        private readonly IMapper _mapper;

        public CategoryDto Category { get; set; }
        
        public SelectList Categories { get; set; }

        [BindProperty]
        public CategoryFormModel FormModel { get; set; }

        public EditModel(ICategoryService reviewService, IMapper mapper)
        {
            _categoryService = reviewService;

            _mapper = mapper;
        }

        public async Task<IActionResult> OnGetAsync([FromRoute] int entityId)
        {
            Category = await _categoryService.GetById<CategoryDto>(entityId);
            var _categories = await _categoryService.GetByFilter<CategoryDto>(new CategoryFilter() { IncludeInactive = true });
            Categories = new SelectList(_categories.OrderBy(x => x.Name), nameof(CategoryDto.EntityId), nameof(CategoryDto.Name));

            FormModel = _mapper.Map<CategoryFormModel>(Category);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromRoute] int entityId)
        {
            if (!ModelState.IsValid)
            {
                return await OnGetAsync(entityId);
            }

            await _categoryService.UpdateById<CategoryDto>(entityId, FormModel);

            return RedirectToPage();
        }
    }
}

TheWebShop.WebApp/Pages/Admin/Products/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using TheWebShop.Common.Dtos;
using TheWebShop.Common.Filters.Brand;
using TheWebShop.Common.Models;
using TheWebShop.Common.Models.Product;
using TheWebShop.Data.Entities.Product;
using TheWebShop.Services.EntityServices.BrandService;
using TheWebShop.Services.EntityServices.ProductService;

namespace TheWebShop.WebApp.Pages.Admin.Products
{
    public class CreateModel : PageModel
    {
        private readonly IProductService _productService;

        private readonly IBrandService _brandService;

        private readonly IWebHostEnvironment _webHostEnvironment;

        private readonly IMapper _mapper;
        
        public SelectList Brands { get; set; }
        
        [BindProperty]
        public IFormFileCollection Pictures { get; set; }
        
        [BindProperty]
        public ProductFormModel FormModel { get; set; }
        
        public CreateModel(IProductService productService, IBrandService brandService, IWebHostEnvironment webHostEnvironment, IMapper mapper)
        {
            _productService = productService;
            _brandService = brandService;

            _webHostEnvironment = webHostEnvironment;
            _mapper = mapper;
        }
        
        public async Task<IActionResult> OnGetAsync()
        {
            var brands = await _brandService.GetByFilter<BrandDto>(new BrandFilter() { PageSize = 0 });
            Brands = new SelectList(brands, nameof(BrandDto.EntityId), nameof(BrandDto.Name));

            return Page();
        }
        
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return await OnGetAsync();
            }

            var entity = _mapper.Map<ProductEntity>(FormModel);
            
            var product = await _productService.Create<ProductDto>(entity);

            if (Pictures != null)
            {
                var productPictures = new List<ProductPictureDto>();
                var uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");

                foreach (var picture in Pictures)
                {
                    var uniqueName = $"{DateTime.Now.ToFileTimeUtc()}-{Guid.NewGuid()}".ToUpper();
                    var filename = $"{uniqueName}.{picture.FileName.Split(".").Last()}";
                    var filePath = Path.Combine(uploadsFolder, filename);
                    await using var fileStream = new FileStream(filePath, FileMode.Create);

                    await picture.CopyToAsync(fileStream);

                    productPictures.Add(new ProductPictureDto()
                    {
                        Picture = filename,
                        Caption = picture.Name
                    });
                }

                await _productService.UploadPictures(product.EntityId, productPictures);
            }

            return RedirectToPage("/Admin/Products/Edit", new { entityId = product.EntityId });   
        }
    }
}

TheWebShop.WebApp/Pages/Admin/Products/Delete.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheWebShop.Common.Dtos;
using TheWebShop.Services.EntityServices.ProductService;

namespace TheWebShop.WebApp.Pages.Admin.Products
{
    public class DeleteModel : PageModel
    {
        private readonly IProductService _productService;
        
        public ProductDto Product { get; set; }

        public DeleteModel(IProductService productService)
        {
            _productService = productService;
        }
        
        public async Task<IActionResult> OnGetAsync([FromRoute] int entityId)
        {
            Product = await _productService.GetById<ProductDto>(entityId);
            
            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromRoute] int entityId)
        {
            await _productService.DeleteById(entityId);
            return RedirectToPage("/Admin/Products/Index");
        }
    }
}

TheWebShop.WebApp/Pages/Admin/Products/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using TheWebShop.Common.Dtos;
using TheWebShop.Common.Filters.Brand;
using TheWebShop.Common.Models;
using TheWebShop.Common.Models.Product;
using TheWebShop.Data.Entities.Product;
using TheWebShop.Services.DataAccessServices.Brand;
using TheWebShop.Services.DataAccessServices.Product;
using TheWebShop.Services.EntityServices.BrandService;
using TheWebShop.Services.EntityServices.ProductService;

namespace TheWebShop.WebApp.Pages.Admin.Products
{
    public class EditModel : PageModel
    {
        private readonly IProductService _productService;

        private readonly IBrandService _brandService;

        private readonly IWebHostEnvironment _webHostEnvironment;

        private readonly IMapper _mapper;
        
        public ProductDto Product { get; set; }
        
        public IEnumerable<ProductPictureDto> ProductPictures { get; set; }
        
        public SelectList Brands { get; set; }
        
        [BindProperty]
        public IFormFileCollection Pictures { get; set; }
        
        [BindProperty]
        public ProductFormModel FormModel { get; set; }

        public EditModel(IProductService productService, IBrandService brandService, IWebHostEnvironment webHostEnvironment, IMapper mapper)
        {
            _productService = productService;
            _brandService = brandService;

            _webHostEnvironment = webHostEnvironment;
            _mapper = mapper;
        }
        
        public async Task<IActionResult> OnGetAsync([FromRoute] int entityId)
        {
            Product = await _productService.GetById<ProductDto>(entityId);
            ProductPictures = await _productService.GetPicturesForProduct(entityId);
            
            var brands = await _brandService.GetByFilter<BrandDto>(new BrandFilter() { PageSize = 0 });
            Brands = new SelectList(brands, nameof(BrandDto.EntityId), nameof(BrandDto.Name), Product.Brand != null ? brands.FirstOrDefault(x => x.EntityId == Product.Brand.EntityId) : null);

            FormModel = _mapper.Map<ProductFormModel>(Product);
            
            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromRoute] int entityId)
        {
            if (!ModelState.IsValid)
            {
                return await OnGetAsync(entityId);
            }

            var product = await _productService.UpdateById<ProductDto>(entityId, FormModel);
            
            if (Pictures != null)
            {
                var productPictures = new List<ProductPictureDto>();
                var uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                
                foreach (var picture in Pictures)
                {
                    var uniqueName = $"{DateTime.Now.ToFileTimeUtc()}-{Guid.NewGuid()}".ToUpper();
                    var filename = $"{uniqueName}.{picture.FileName.Split(".").Last()}";
                    var filePath = Path.Combine(uploadsFolder, filename);
                    await using var fileStream = new FileStream(filePath, FileMode.Create);

                    await picture.CopyToAsync(fileStream);

                    productPictures.Add(new ProductPictureDto()
                    {
                        Picture = filename,
                        Caption = picture.Name
                    });
                }

                await _productService.UploadPictures(product.EntityId, productPictures);
            }
            
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemovePicture([FromRoute] int entityId, int pictureId)
        {
            await _productService.DeletePictureById(pictureId);
            return RedirectToPage();
        }
    }
}

TheWebShop.WebApp/Pages/Admin/Products/Create.cshtml
@page
@model CreateModel
@{
    ViewData["Title"] = "Create a new product";
}

<form method="post" enctype="multipart/form-data">

    <div class="form-row">
        <div class="col-md-12">

            <div class="form-group">
                <div class="input-group">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" multiple asp-for="@Model.Pictures">
                        <label class="custom-file-label" asp-for="@Model.Pictures" aria-describedby="Pictures">Choose file</label>
                        <small class="text-danger">
                            @Html.ValidationMessageFor(x => x.Pictures)
                        </small>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="form-row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="@Model.FormModel.Name"></label>
                <input type="text" class="form-control" asp-for="@Model.FormModel.Name" />
                <small class="text-danger">
                    @Html.ValidationMessageFor(x => x.FormModel.Name)
                </small>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label>Brand</label>
                <select class="custom-select" asp-for="@Model.FormModel.BrandEntityId" asp-items="@Model.Brands">
                    <option value="@null" selected>None</option>
                    <small class="text-danger">
                        @Html.ValidationMessageFor(x => x.FormModel.BrandEntityId)
                    </small>
                </select>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="@Model.FormModel.Price"></label>
                <input type="text" class="form-control" asp-for="@Model.FormModel.Price" />
                <small class="text-danger">
                    @Html.ValidationMessageFor(x => x.FormModel.Price)
                </small>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="@Model.FormModel.Stock"></label>
                <input type="number" class="form-control" asp-for="@Model.FormModel.Stock" />
                <small class="text-danger">
                    @Html.ValidationMessageFor(x => x.FormModel.Stock)
                </small>
            </div>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-12">
            <div class="form-group">
                <label asp-for="@Model.FormModel.Description"></label>
                <textarea class="form-control" rows="8" asp-for="@Model.FormModel.Description"></textarea>
                <small class="text-danger">
                    @Html.ValidationMessageFor(x => x.FormModel.Description)
                </small>
            </div>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-6">
            <div class="form-group">
                <div class="form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" asp-for="@Model.FormModel.Active">
                        Active
                    </label>
                    <small class="d-block text-muted">Should this product be shown throughout the website?</small>
                    <small class="d-block text-danger">
                        @Html.ValidationMessageFor(x => x.FormModel.Active)
                    </small>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <div class="form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" asp-for="@Model.FormModel.Highlight">
                        Highlight
                    </label>
                    <small class="d-block text-muted">Should this product be highlighted?</small>
                    <small class="d-block text-danger">
                        @Html.ValidationMessageFor(x => x.FormModel.Highlight)
                    </small>
                </div>
            </div>
        </div>
    </div>

    <div class="d-flex">
        <a class="btn btn-light mr-1" asp-page="/Admin/Products/Index"><i class="fas fa-arrow-left fa-fw mr-2"></i>Back</a>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>

</form>

TheWebShop.WebApp/Pages/Admin/Products/Delete.cshtml
@page "/Admin/Products/{entityId}/Delete"
@model DeleteModel

@{
    ViewData["Title"] = Model.Product.Name;
}

<form method="post">
    <h3>You're about to delete <code>@Model.Product.Name</code></h3>
    <p>Are you sure you want to delete <code>@Model.Product.Name</code>?</p>
    <div class="d-flex">
        <button type="button" class="btn btn-light btn-block mr-3" onclick="history.go(-1)">Cancel</button>
        <button type="submit" class="btn btn-danger btn-block mt-0">Delete</button>
    </div>
</form>

TheWebShop.WebApp/Pages/Admin/Products/Edit.cshtml
@page "/Admin/Products/{entityId}/Edit"
@model EditModel
@{
    ViewData["Title"] = Model.Product.Name;
}

<form id="picturesForm" method="post" asp-page-handler="RemovePicture">

    <div class="mb-3" style="display:grid;grid-template-columns:repeat(auto-fill, minmax(240px, 1fr));grid-gap:1rem;">

        <input type="hidden" id="pictureId" name="pictureId"/>

        @foreach (var item in Model.ProductPictures)
        {
            <div class="position-relative rounded" style="padding-bottom:calc(9/16 * 100%);background-image: url('/images/@item.Picture');background-position: center;background-repeat: no-repeat;background-size: cover;">
                <div class="position-absolute" style="bottom:1rem;right:1rem;">
                    <button class="btn btn-danger btn-sm js-remove" data-pictureid="@item.EntityId">
                        <i class="fas fa-trash fa-fw"></i>
                    </button>
                </div>
            </div>
        }

    </div>

</form>

<script>
    $(document).ready(function() {
       
        $(".js-remove").click(function (e) {
            $("#pictureId").val(this.dataset.pictureid);
            $("#picturesForm").submit();
        });
        
    });
</script>

<form method="post" enctype="multipart/form-data">

    <div class="form-row">
        <div class="col-md-12">

            <div class="form-group">
                <div class="input-group">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" multiple asp-for="@Model.Pictures">
                        <label class="custom-file-label" asp-for="@Model.Pictures" aria-describedby="Pictures">Choose file</label>
                        <small class="text-danger">
                            @Html.ValidationMessageFor(x => x.Pictures)
                        </small>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="form-row">
        <div class="col-md-12">
            <div class="form-group">
                <label asp-for="@Model.Product.EntityId"></label>
                <input type="text" class="form-control" readonly asp-for="@Model.Product.EntityId" />
            </div>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="@Model.Product.Name"></label>
                <input type="text" class="form-control" asp-for="@Model.FormModel.Name" />
                <small class="text-danger">
                    @Html.ValidationMessageFor(x => x.FormModel.Name)
                </small>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="@Model.Product.Brand"></label>
                <select class="custom-select" asp-for="@Model.FormModel.BrandEntityId" asp-items="@Model.Brands">
                    <option value="@null" selected>None</option>
                </select>
                <small class="text-danger">
                    @Html.ValidationMessageFor(x => x.FormModel.BrandEntityId)
                </small>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="@Model.Product.Price"></label>
                <input type="text" class="form-control" asp-for="@Model.FormModel.Price" />
                <small class="text-danger">
                    @Html.ValidationMessageFor(x => x.FormModel.Price)
                </small>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="@Model.Product.Stock"></label>
                <input type="number" class="form-control" asp-for="@Model.FormModel.Stock" />
                <small class="text-danger">
                    @Html.ValidationMessageFor(x => x.FormModel.Stock)
                </small>
            </div>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-12">
            <div class="form-group">
                <label asp-for="@Model.Product.Description"></label>
                <textarea class="form-control" rows="8" asp-for="@Model.FormModel.Description"></textarea>
                <small class="text-danger">
                    @Html.ValidationMessageFor(x => x.FormModel.Description)
                </small>
            </div>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-6">
            <div class="form-group">
                <div class="form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" asp-for="@Model.FormModel.Active">
                        Active
                    </label>
                    <small class="d-block text-muted">Should this product be shown throughout the website?</small>
                    <small class="d-block text-danger">
                        @Html.ValidationMessageFor(x => x.FormModel.Active)
                    </small>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <div class="form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" asp-for="@Model.FormModel.Highlight">
                        Highlight
                    </label>
                    <small class="d-block text-muted">Should this product be highlighted?</small>
                    <small class="d-block text-danger">
                        @Html.ValidationMessageFor(x => x.FormModel.Highlight)
                    </small>
                </div>
            </div>
        </div>
    </div>

    <div class="d-flex">
        <a class="btn btn-light mr-1" asp-page="/Admin/Products/Index"><i class="fas fa-arrow-left fa-fw mr-2"></i>Back</a>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>

</form>